version: "3"
services:
  web: # Name of the service that will run i.e. web, rename accordingly
    # replace username/repo:tag with your name and image details - this will issue docker pull
    image:  username/repo:tag
    deploy:
      # Number of instances to replicate
      replicas: 1
      # Always restart on any failure asap
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet: